// <auto-generated />
using System;
using MedicSoft.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MedicSoft.Repository.Migrations.PostgreSQL
{
    [DbContext(typeof(MedicSoftDbContext))]
    [Migration("20260128190000_AddTagAndClinicTagTables")]
    partial class AddTagAndClinicTagTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // This is a minimal snapshot - the actual model is defined in the main migration
#pragma warning restore 612, 618
        }
    }
}
