version: '3.8'

# Podman Compose para PrimeCare Software - Ambiente de Desenvolvimento
# Este arquivo também é compatível com Docker Compose
#
# Executar com Podman (recomendado - livre e open-source):
#   podman-compose up -d
#
# Ou com Docker (alternativa):
#   docker-compose up -d

services:
  postgres:
    image: postgres:16-alpine
    container_name: primecare-postgres
    environment:
      POSTGRES_DB: primecare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db-postgres.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - primecare-network
    healthcheck:
      test: pg_isready -U postgres -d primecare
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: src/MedicSoft.Api/Dockerfile
    container_name: primecare-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=primecare;Username=postgres;Password=${POSTGRES_PASSWORD:-postgres};Include Error Detail=true
      - JwtSettings__SecretKey=${JWT_SECRET_KEY:-PrimeCare Software-SuperSecretKey-2024-Development-MinLength32Chars!}
      - JwtSettings__ExpiryMinutes=60
      - JwtSettings__Issuer=PrimeCare Software
      - JwtSettings__Audience=PrimeCare Software-API
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - primecare-network

  frontend:
    build:
      context: ./frontend/primecare-app
      dockerfile: Dockerfile
    container_name: primecare-frontend
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - primecare-network

  system-admin:
    build:
      context: ./frontend/mw-system-admin
      dockerfile: Dockerfile
    container_name: primecare-system-admin
    ports:
      - "4201:4200"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - primecare-network

volumes:
  postgres_data:

networks:
  primecare-network:
    driver: bridge
