// <auto-generated />
using System;
using MedicSoft.Telemedicine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicSoft.Telemedicine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TelemedicineDbContext))]
    partial class TelemedicineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicSoft.Telemedicine.Domain.Entities.TelemedicineSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoomUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SessionNotes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AppointmentId");

                    b.HasIndex("TenantId", "ClinicId");

                    b.HasIndex("TenantId", "PatientId");

                    b.HasIndex("TenantId", "ProviderId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("TelemedicineSessions", (string)null);
                });

            modelBuilder.Entity("MedicSoft.Telemedicine.Domain.Entities.TelemedicineSession", b =>
                {
                    b.OwnsOne("MedicSoft.Telemedicine.Domain.ValueObjects.SessionDuration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("TelemedicineSessionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("EndTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TelemedicineSessionId");

                            b1.ToTable("TelemedicineSessions");

                            b1.WithOwner()
                                .HasForeignKey("TelemedicineSessionId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
